/**
 * Template loading and validation for response_template objects.
 */

import { logger } from '../logger.js';
import { CONTENT_PARSERS, validate_transform_strings } from './content_parsers.js';
import { compile_pattern, escape_pattern } from './regex.js';

/**
 * @typedef {import('./regex.js').CompiledPattern & { literals: string[]|null, literal_can_extend: boolean }} Anchor
 * A compiled delimiter. `literals` holds the literal strings for `open`/`close`/`start_anchor`
 * (or `null` for a `*_pattern` regex), and `literal_can_extend` is `true` iff one literal is a
 * strict prefix of another.
 */

/**
 * @typedef {Object} ResponseTemplateField
 * @property {string} name
 * @property {Anchor|null} open
 * @property {Anchor|null} close
 * @property {string} content
 * @property {Object} content_args
 * @property {boolean} repeats
 * @property {string|null} join
 * @property {boolean} optional
 * @property {any} transform
 * @property {boolean} transform_each
 */

/**
 * @typedef {Object} ResponseTemplate
 * @property {Record<string, any>} defaults
 * @property {Record<string, ResponseTemplateField>} fields
 * @property {Anchor} start_anchor
 * @property {string|null} implicit
 */

const TEMPLATE_KEYS = new Set(['version', 'defaults', 'fields', 'start_anchor', 'start_anchor_pattern']);
const FIELD_KEYS = new Set([
    'open',
    'open_pattern',
    'close',
    'close_pattern',
    'content',
    'content_args',
    'repeats',
    'join',
    'optional',
    'transform',
    'transform_each',
]);

const is_object = (value) => value !== null && typeof value === 'object' && !Array.isArray(value);
const type_name = (value) => (value === null ? 'null' : Array.isArray(value) ? 'array' : typeof value);
const unknown_keys = (object, allowed) =>
    Object.keys(object)
        .filter((key) => !allowed.has(key))
        .sort();

/**
 * When parsing responses, we can't just parse the tokens generated by the model. This is because chat
 * templates often include early parts of the message such as <start_of_turn> or <think> tokens in the
 * prefill. Therefore, we take the whole chat as input, but truncate to the start of the most recent
 * assistant message, which can include tokens from the template as well as the output.
 * @param {ResponseTemplate} template The loaded template.
 * @param {string} text The chat prompt.
 * @returns {string}
 */
export function truncate_past_last_anchor(template, text) {
    let last_end = null;
    for (const m of text.matchAll(template.start_anchor.regex)) {
        last_end = m.index + m[0].length;
    }
    if (last_end === null) {
        const kind = template.start_anchor.literals !== null ? 'start_anchor' : 'start_anchor_pattern';
        logger.info(
            `response_template defines ${kind} but the anchor was not found ` +
                'in the prefix; the parser will process the entire prefix instead.',
        );
        return text;
    }
    return text.slice(last_end);
}

/**
 * Compile a region's start/end anchor. An anchor can be:
 *
 * - a regex (`pattern_key`),
 * - a single literal string (`literal_key`), or
 * - a list of literal strings (`literal_key`), in which case any of these match
 *
 * All forms compile to a regex for matching, but we keep the literal strings around too: a finished
 * literal match can never be extended by future input (except when a literal is a strict prefix of
 * another in the same list), so the parser can emit regions without waiting for more input.
 * @returns {Anchor|null}
 */
function compile_anchor(scope, field, literal_key, pattern_key) {
    if (Object.hasOwn(field, literal_key) && Object.hasOwn(field, pattern_key)) {
        throw new Error(`${scope}: cannot specify both '${literal_key}' and '${pattern_key}'`);
    }
    if (Object.hasOwn(field, literal_key)) {
        const raw = field[literal_key];
        let literals;
        if (typeof raw === 'string') {
            literals = [raw];
        } else if (Array.isArray(raw)) {
            if (raw.length === 0) throw new Error(`${scope}: '${literal_key}' list must contain at least one literal`);
            if (!raw.every((s) => typeof s === 'string')) {
                throw new Error(`${scope}: '${literal_key}' list must contain only strings`);
            }
            literals = [...new Set(raw)]; // dedupe, preserve first-seen order
        } else {
            throw new Error(`${scope}: '${literal_key}' must be a string or list of strings, got ${type_name(raw)}`);
        }
        if (literals.includes('')) throw new Error(`${scope}: '${literal_key}' literals cannot be empty strings`);
        // Sort longest-first so alternation prefers the longer alternative when both could match.
        const ordered = [...literals].sort((a, b) => b.length - a.length);
        const literal_can_extend = literals.some((a) => literals.some((b) => a !== b && a.startsWith(b)));
        return { ...compile_pattern(ordered.map(escape_pattern).join('|')), literals, literal_can_extend };
    }
    if (Object.hasOwn(field, pattern_key)) {
        try {
            return { ...compile_pattern(field[pattern_key]), literals: null, literal_can_extend: false };
        } catch (e) {
            throw new Error(`${scope}: invalid ${pattern_key} regex: ${e.message}`);
        }
    }
    return null;
}

/**
 * Validate the top-level response_template structure: it must be an object of the expected version with
 * only known keys, an object of `defaults`, and a non-empty object of `fields`. Per-field specs are checked
 * separately in `build_field`.
 */
function validate_template_shape(spec) {
    if (!is_object(spec)) throw new Error(`response_template must be an object, got ${type_name(spec)}`);
    const version = spec.version ?? 1;
    if (version !== 1) throw new Error(`Unsupported response_template version: ${version}`);
    const unknown = unknown_keys(spec, TEMPLATE_KEYS);
    if (unknown.length) throw new Error(`Unknown keys in response_template: ${JSON.stringify(unknown)}`);
    if (!is_object(spec.defaults ?? {})) throw new Error('response_template.defaults must be an object');
    const fields = spec.fields ?? {};
    if (!is_object(fields) || Object.keys(fields).length === 0) {
        throw new Error('response_template.fields must be a non-empty object');
    }
}

/**
 * Validate a single field spec and compile it into a `ResponseTemplateField`.
 * @returns {ResponseTemplateField}
 */
function build_field(name, field) {
    const scope = `Field '${name}'`;
    if (!is_object(field)) throw new Error(`${scope} must be an object`);
    const unknown = unknown_keys(field, FIELD_KEYS);
    if (unknown.length) throw new Error(`${scope}: unknown keys ${JSON.stringify(unknown)}`);
    const content = field.content ?? 'text';
    if (!Object.hasOwn(CONTENT_PARSERS, content)) {
        throw new Error(
            `${scope}: unknown content parser '${content}'. Available: ${JSON.stringify(Object.keys(CONTENT_PARSERS).sort())}`,
        );
    }
    const open = compile_anchor(scope, field, 'open', 'open_pattern');
    const close = compile_anchor(scope, field, 'close', 'close_pattern');
    const join = field.join ?? null;
    if (join !== null && typeof join !== 'string') {
        throw new Error(`${scope}: 'join' must be a string, got ${type_name(join)}`);
    }
    if (join !== null && !field.repeats) throw new Error(`${scope}: 'join' requires 'repeats': true`);
    const transform = field.transform ?? null;
    const transform_each = field.transform_each ?? false;
    if (typeof transform_each !== 'boolean') {
        throw new Error(`${scope}: transform_each must be a bool, got ${type_name(transform_each)}`);
    }
    if (transform_each && transform === null) {
        throw new Error(`${scope}: transform_each is set but no transform was provided`);
    }
    if (transform !== null) {
        validate_transform_strings(scope, transform);
    } else {
        // Named captures only reach the output through a transform, so flag any that would be silently dropped.
        const captured_names = [...new Set([...(open?.names ?? []), ...(close?.names ?? [])])].sort();
        if (captured_names.length) {
            throw new Error(
                `${scope}: open_pattern/close_pattern declares named group(s) ` +
                    `${JSON.stringify(captured_names)}, but the field has no 'transform'. Named captures ` +
                    `are only surfaced through a 'transform' template (where they appear ` +
                    `alongside 'content'). Either add a 'transform' that uses the captures, or ` +
                    `remove the named groups from the pattern.`,
            );
        }
    }
    return {
        name,
        open,
        close,
        content,
        content_args: field.content_args ?? {},
        repeats: field.repeats ?? false,
        join,
        optional: field.optional ?? true,
        transform,
        transform_each,
    };
}

/**
 * Validate a response_template and compile its delimiters.
 * @param {Object} spec The response_template.
 * @returns {ResponseTemplate}
 */
export function load_response_template(spec) {
    validate_template_shape(spec);

    const fields = Object.fromEntries(Object.entries(spec.fields).map(([name, raw]) => [name, build_field(name, raw)]));
    // A field without an open anchor is the implicit-open / leftover sink; at most one is allowed.
    const implicit_fields = Object.values(fields)
        .filter((field) => field.open === null)
        .map((field) => field.name);
    if (implicit_fields.length > 1) {
        throw new Error(
            "At most one field may omit 'open'/'open_pattern' (that field becomes the " +
                `implicit-open / leftover sink). Found: ${implicit_fields.join(', ')}`,
        );
    }

    const start_anchor = compile_anchor('response_template', spec, 'start_anchor', 'start_anchor_pattern');
    if (start_anchor === null) {
        throw new Error("response_template must define 'start_anchor' or 'start_anchor_pattern'.");
    }

    return {
        defaults: { ...(spec.defaults ?? {}) },
        fields,
        implicit: implicit_fields[0] ?? null,
        start_anchor,
    };
}
